### ISSUE TITLE
Add reconnection params for java clients

### ISSUE THREAD

**Issue by MichaelHussey** [confluentinc/configuration-templates#7]
In the snippet for Java CCloud configuration-templates/clients/cloud/java.config there are no reconnection parameters.

In https://docs.confluent.io/current/cloud/using/config-client.html#java-client there are 
```
request.timeout.ms=20000
retry.backoff.ms=500
```
Should these be present in all CCloud client examples? If so, ideally with some comments pointing out how important they are.

**Comment by ybyzek** [comment]
@MichaelHussey on the contrary, those are being removed from all examples: https://github.com/confluentinc/docs/pull/4730

And others added in their stead: https://github.com/confluentinc/configuration-templates/pull/6

**Comment by MichaelHussey** [comment]
Thanks @ybyzek - I didn't realise that this is the canonical reference and the docs lag it.

**Comment by ybyzek** [comment]
Haha, I don't know about "canonical" but yeah 👍
